# Generated by Django 3.1.3 on 2020-11-16 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_wisdomnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_one', models.CharField(default='Miscellaneous', max_length=120)),
                ('assigned_tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.newstags')),
            ],
        ),
    ]
