# Generated by Django 3.1.3 on 2020-11-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_newscategory_newstags'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=120)),
                ('quest_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='newscategory',
            name='assigned_tag',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.DeleteModel(
            name='WisdomNote',
        ),
        migrations.DeleteModel(
            name='NewsCategory',
        ),
        migrations.DeleteModel(
            name='NewsTags',
        ),
    ]
