# Generated by Django 3.1.3 on 2020-11-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address_one',
            field=models.CharField(default=1, max_length=280),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='address_two',
            field=models.CharField(default=2, max_length=280),
            preserve_default=False,
        ),
    ]
