# Generated by Django 3.1.3 on 2020-12-01 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20201126_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='company',
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.company'),
            preserve_default=False,
        ),
    ]
