# Generated by Django 3.1.3 on 2020-12-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20201201_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(default='logo.jpg', upload_to='company_pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_logo',
            field=models.ImageField(default='product.jpg', upload_to='product_pics'),
        ),
    ]
