# Generated by Django 3.1.3 on 2020-11-28 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20201126_1722'),
        ('users', '0003_auto_20201120_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.company'),
        ),
    ]
